version: '3.9'
services:
  users_dev:
    extends:
      file: ./docker-compose.prod.yml
      service: users
    build:
      context: ./
      dockerfile: ../development.Dockerfile
    ports:
      - target: ${USERS_INSIDE_PORT}
        published: ${USERS_INSIDE_PORT}
        protocol: tcp
        mode: host
    volumes:
      - ./:/var/www/html
    command: ${USERS_RUN_COMMAND}